sudo: required
services:
  - docker

before_install:
  - docker build -t ropto/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ropto/react-test npm test -- --coverage

after_success:
  - docker build -t ropto/multi-client ./client
  - docker build -t ropto/multi-nginx ./nginx
  - docker build -t ropto/multi-api ./api
  - docker build -t ropto/multi-worker ./worker
  
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to docker hub
  - docker push ropto/multi-client
  - docker push ropto/multi-nginx
  - docker push ropto/multi-api
  - docker push ropto/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-075768480549"
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY